# Generated by Django 5.1.5 on 2025-01-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_books.genre', verbose_name='Жанр'),
        ),
    ]
